// Maps team slugs to ESPN team IDs for API calls
export const teamSlugToEspnId: Record<string, number> = {
  // SEC
  'alabama-crimson-tide': 333,
  'arkansas-razorbacks': 8,
  'auburn-tigers': 2,
  'florida-gators': 57,
  'georgia-bulldogs': 61,
  'kentucky-wildcats': 96,
  'lsu-tigers': 99,
  'ole-miss-rebels': 145,
  'mississippi-state-bulldogs': 344,
  'missouri-tigers': 142,
  'oklahoma-sooners': 201,
  'south-carolina-gamecocks': 2579,
  'tennessee-volunteers': 2633,
  'texas-longhorns': 251,
  'texas-am-aggies': 245,
  'vanderbilt-commodores': 238,

  // Big Ten
  'illinois-fighting-illini': 356,
  'indiana-hoosiers': 84,
  'iowa-hawkeyes': 2294,
  'maryland-terrapins': 120,
  'michigan-wolverines': 130,
  'michigan-state-spartans': 127,
  'minnesota-golden-gophers': 135,
  'nebraska-cornhuskers': 158,
  'northwestern-wildcats': 77,
  'ohio-state-buckeyes': 194,
  'oregon-ducks': 2483,
  'penn-state-nittany-lions': 213,
  'purdue-boilermakers': 2509,
  'rutgers-scarlet-knights': 164,
  'ucla-bruins': 26,
  'usc-trojans': 30,
  'washington-huskies': 264,
  'wisconsin-badgers': 275,

  // Big 12
  'arizona-wildcats': 12,
  'arizona-state-sun-devils': 9,
  'baylor-bears': 239,
  'byu-cougars': 252,
  'cincinnati-bearcats': 2132,
  'colorado-buffaloes': 38,
  'houston-cougars': 248,
  'iowa-state-cyclones': 66,
  'kansas-jayhawks': 2305,
  'kansas-state-wildcats': 2306,
  'oklahoma-state-cowboys': 197,
  'tcu-horned-frogs': 2628,
  'texas-tech-red-raiders': 2641,
  'ucf-knights': 2116,
  'utah-utes': 254,
  'west-virginia-mountaineers': 277,

  // ACC
  'boston-college-eagles': 103,
  'california-golden-bears': 25,
  'clemson-tigers': 228,
  'duke-blue-devils': 150,
  'florida-state-seminoles': 52,
  'georgia-tech-yellow-jackets': 59,
  'louisville-cardinals': 97,
  'miami-hurricanes': 2390,
  'north-carolina-tar-heels': 153,
  'nc-state-wolfpack': 152,
  'pittsburgh-panthers': 221,
  'smu-mustangs': 2567,
  'stanford-cardinal': 24,
  'syracuse-orange': 183,
  'virginia-cavaliers': 258,
  'virginia-tech-hokies': 259,
  'wake-forest-demon-deacons': 154,

  // American
  'army-black-knights': 349,
  'charlotte-49ers': 2429,
  'east-carolina-pirates': 151,
  'fau-owls': 2226,
  'memphis-tigers': 235,
  'navy-midshipmen': 2426,
  'north-texas-mean-green': 249,
  'rice-owls': 242,
  'south-florida-bulls': 58,
  'temple-owls': 218,
  'tulane-green-wave': 2655,
  'tulsa-golden-hurricane': 202,
  'uab-blazers': 5,
  'utsa-roadrunners': 2636,

  // Pac-12
  'washington-state-cougars': 265,
  'oregon-state-beavers': 204,

  // Mountain West
  'air-force-falcons': 2005,
  'boise-state-broncos': 68,
  'colorado-state-rams': 36,
  'fresno-state-bulldogs': 278,
  'hawaii-rainbow-warriors': 62,
  'nevada-wolf-pack': 2440,
  'new-mexico-lobos': 167,
  'san-diego-state-aztecs': 21,
  'san-jose-state-spartans': 23,
  'unlv-rebels': 2439,
  'utah-state-aggies': 328,
  'wyoming-cowboys': 2704,

  // Sun Belt
  'appalachian-state-mountaineers': 2026,
  'arkansas-state-red-wolves': 2032,
  'coastal-carolina-chanticleers': 324,
  'georgia-southern-eagles': 290,
  'georgia-state-panthers': 2247,
  'james-madison-dukes': 256,
  'louisiana-ragin-cajuns': 309,
  'louisiana-monroe-warhawks': 2433,
  'marshall-thundering-herd': 276,
  'old-dominion-monarchs': 295,
  'south-alabama-jaguars': 6,
  'southern-miss-golden-eagles': 2572,
  'texas-state-bobcats': 326,
  'troy-trojans': 2653,

  // Conference USA
  'missouri-state-bears': 2623,
  'delaware-fightin-blue-hens': 48,
  'fiu-panthers': 2229,
  'jacksonville-state-gamecocks': 55,
  'kennesaw-state-owls': 338,
  'liberty-flames': 2335,
  'louisiana-tech-bulldogs': 2348,
  'middle-tennessee-blue-raiders': 2393,
  'new-mexico-state-aggies': 166,
  'sam-houston-bearkats': 2534,
  'utep-miners': 2638,
  'western-kentucky-hilltoppers': 98,

  // Independents
  'uconn-huskies': 41,
  'notre-dame-fighting-irish': 87,

  // MAC
  'akron-zips': 2006,
  'ball-state-cardinals': 2050,
  'bowling-green-falcons': 189,
  'buffalo-bulls': 2084,
  'central-michigan-chippewas': 2117,
  'eastern-michigan-eagles': 2199,
  'kent-state-golden-flashes': 2309,
  'umass-minutemen': 113,
  'miami-oh-redhawks': 193,
  'northern-illinois-huskies': 2459,
  'ohio-bobcats': 195,
  'toledo-rockets': 2649,
  'western-michigan-broncos': 2711,
};

export function getEspnIdFromSlug(slug: string): number | undefined {
  return teamSlugToEspnId[slug];
}
