// CFB Team Logos
const cfbTeams: Record<string, string> = {
  // SEC
  'alabama': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ALA.png',
  'arkansas': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ARK.png',
  'auburn': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/AUB.png',
  'florida': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FLA.png',
  'georgia': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UGA.png',
  'kentucky': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UK.png',
  'lsu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LSU.png',
  'mississippi': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MISS.png',
  'ole miss': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MISS.png',
  'mississippi state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MSST.png',
  'missouri': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MIZ.png',
  'oklahoma': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/OU.png',
  'south carolina': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SC.png',
  'tennessee': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TENN.png',
  'texas': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TEX.png',
  'texas a&m': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TA&M.png',
  'vanderbilt': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/VAN.png',

  // Big Ten
  'illinois': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ILL.png',
  'indiana': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/IU.png',
  'iowa': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/IOWA.png',
  'maryland': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MD.png',
  'michigan': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MICH.png',
  'michigan state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MSU.png',
  'minnesota': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MINN.png',
  'nebraska': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NEB.png',
  'northwestern': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NU.png',
  'northwestern university': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NU.png',
  'northwestern wildcats': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NU.png',
  'nw': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NU.png',
  'nu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NU.png',
  'ohio state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/OSU.png',
  'oregon': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ORE.png',
  'penn state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PSU.png',
  'purdue': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PUR.png',
  'rutgers': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/RUTG.png',
  'ucla': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UCLA.png',
  'usc': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/USC.png',
  'washington': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WASH.png',
  'wisconsin': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WIS.png',

  // Big 12
  'arizona': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ARIZ.png',
  'arizona state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ASU.png',
  'baylor': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BAY.png',
  'byu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BYU.png',
  'cincinnati': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CIN.png',
  'colorado': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/COLO.png',
  'houston': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/HOU.png',
  'iowa state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ISU.png',
  'kansas': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/KU.png',
  'kansas state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/KSU.png',
  'oklahoma state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/OKST.png',
  'tcu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TCU.png',
  'texas tech': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TTU.png',
  'ucf': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UCF.png',
  'utah': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UTAH.png',
  'west virginia': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WVU.png',

  // ACC
  'boston college': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BC.png',
  'california': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CAL.png',
  'clemson': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CLEM.png',
  'duke': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/DUKE.png',
  'florida state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FSU.png',
  'georgia tech': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/GT.png',
  'louisville': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LOU.png',
  'miami': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MIA.png',
  'miami (fl)': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MIA.png',
  'north carolina': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UNC.png',
  'north carolina state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NCSU.png',
  'nc state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NCSU.png',
  'nc state wolfpack': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NCSU.png',
  'ncsu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NCSU.png',
  'pittsburgh': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PITT.png',
  'pitt': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PITT.png',
  'smu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SMU.png',
  'stanford': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/STAN.png',
  'syracuse': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SYR.png',
  'virginia': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UVA.png',
  'virginia tech': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/VT.png',
  'wake forest': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WAKE.png',

  // American/AAC
  'army': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ARMY.png',
  'charlotte': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CLT.png',
  'east carolina': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ECU.png',
  'fau': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FAU.png',
  'memphis': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MEM.png',
  'navy': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NAVY.png',
  'north texas': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UNT.png',
  'rice': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/RICE.png',
  'usf': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/USF.png',
  'temple': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TEM.png',
  'tulane': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TULN.png',
  'tulsa': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TLSA.png',
  'uab': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UAB.png',
  'utsa': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UTSA.png',

  // PAC-12
  'washington state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WSU.png',
  'oregon state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ORST.png',

  // Mountain West
  'air force': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/AFA.png',
  'boise state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BOIS.png',
  'colorado state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CSU.png',
  'fresno state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FRES.png',
  'hawaii': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/HAW.png',
  'nevada': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NEV.png',
  'new mexico': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UNM.png',
  'san diego state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SDSU.png',
  'san jose state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SJSU.png',
  'unlv': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UNLV.png',
  'utah state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/USU.png',
  'wyoming': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WYO.png',

  // Sun Belt
  'appalachian state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/APP.png',
  'arkansas state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ARST.png',
  'coastal carolina': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CCU.png',
  'georgia southern': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/GASO.png',
  'georgia state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/GAST.png',
  'james madison': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/JMU.png',
  'jmu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/JMU.png',
  'louisiana': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UL.png',
  'louisiana-monroe': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ULM.png',
  'marshall': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MRSH.png',
  'old dominion': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ODU.png',
  'south alabama': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/USA.png',
  'southern miss': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/USM.png',
  'texas state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TXST.png',
  'troy': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TROY.png',

  // Conference USA
  'delaware': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UD.png',
  'florida international': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FIU.png',
  'fiu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FIU.png',
  'jacksonville state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/JVST.png',
  'kennesaw state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/KENN.png',
  'liberty': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LIB.png',
  'louisiana tech': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LT.png',
  'middle tennessee': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTSU.png',
  'middle tennessee state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTSU.png',
  'middle tennessee state university': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTSU.png',
  'middle tennessee blue raiders': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTSU.png',
  'mtsu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTSU.png',
  'mt': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTSU.png',
  'new mexico state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NMSU.png',
  'sam houston': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SHSU.png',
  'utep': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UTEP.png',
  'western kentucky': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WKU.png',

  // Independents
  'connecticut': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CONN.png',
  'notre dame': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ND.png',

  // MAC
  'akron': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/AKR.png',
  'ball state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BALL.png',
  'bowling green': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BGSU.png',
  'buffalo': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BUFF.png',
  'central michigan': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CMU.png',
  'eastern michigan': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/EMU.png',
  'kent state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/KENT.png',
  'massachusetts': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MASS.png',
  'umass': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MASS.png',
  'miami (oh)': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/M-OH.png',
  'northern illinois': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NIU.png',
  'ohio': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/OHIO.png',
  'toledo': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TOL.png',
  'western michigan': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WMU.png',

  // FCS Notable
  'jackson state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/JSU.png',
}

export function getTeamLogo(teamName: string): string {
  const team = teamName.toLowerCase().trim()
  return cfbTeams[team] || '/logos/default.png'
}
