import { allTeams } from '@/data/teams'

// CFB Team Logos
const cfbTeams: Record<string, string> = {
  // SEC
  'alabama': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ALA.png',
  'arkansas': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ARK.png',
  'auburn': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/AUB.png',
  'florida': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FLA.png',
  'georgia': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UGA.png',
  'kentucky': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UK.png',
  'lsu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LSU.png',
  'mississippi': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MISS.png',
  'ole miss': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MISS.png',
  'mississippi state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MSST.png',
  'missouri': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MIZ.png',
  'oklahoma': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/OU.png',
  'south carolina': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SC.png',
  'tennessee': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TENN.png',
  'texas': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TEX.png',
  'texas a&m': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TA&M.png',
  'vanderbilt': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/VAN.png',

  // Big Ten
  'illinois': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ILL.png',
  'indiana': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/IU.png',
  'iowa': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/IOWA.png',
  'maryland': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MD.png',
  'michigan': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MICH.png',
  'michigan state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MSU.png',
  'minnesota': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MINN.png',
  'nebraska': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NEB.png',
  'northwestern': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NU.png',
  'northwestern university': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NU.png',
  'northwestern wildcats': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NU.png',
  'nw': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NU.png',
  'nu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NU.png',
  'ohio state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/OSU.png',
  'oregon': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ORE.png',
  'penn state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PSU.png',
  'purdue': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PUR.png',
  'rutgers': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/RUTG.png',
  'ucla': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UCLA.png',
  'usc': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/USC.png',
  'washington': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WASH.png',
  'wisconsin': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WIS.png',

  // Big 12
  'arizona': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ARIZ.png',
  'arizona state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ASU.png',
  'baylor': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BAY.png',
  'byu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BYU.png',
  'cincinnati': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CIN.png',
  'colorado': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/COLO.png',
  'houston': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/HOU.png',
  'iowa state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ISU.png',
  'kansas': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/KU.png',
  'kansas state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/KSU.png',
  'oklahoma state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/OKST.png',
  'tcu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TCU.png',
  'texas tech': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TTU.png',
  'ucf': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UCF.png',
  'utah': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UTAH.png',
  'west virginia': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WVU.png',

  // ACC
  'boston college': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BC.png',
  'california': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CAL.png',
  'clemson': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CLEM.png',
  'duke': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/DUKE.png',
  'florida state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FSU.png',
  'georgia tech': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/GT.png',
  'louisville': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LOU.png',
  'miami': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MIA.png',
  'miami (fl)': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MIA.png',
  'north carolina': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UNC.png',
  'north carolina state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NCSU.png',
  'nc state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NCSU.png',
  'nc state wolfpack': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NCSU.png',
  'ncsu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NCSU.png',
  'pittsburgh': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PITT.png',
  'pitt': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PITT.png',
  'smu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SMU.png',
  'stanford': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/STAN.png',
  'syracuse': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SYR.png',
  'virginia': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UVA.png',
  'virginia tech': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/VT.png',
  'wake forest': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WAKE.png',

  // American/AAC
  'army': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ARMY.png',
  'charlotte': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CLT.png',
  'east carolina': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ECU.png',
  'fau': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FAU.png',
  'memphis': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MEM.png',
  'navy': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NAVY.png',
  'north texas': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UNT.png',
  'rice': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/RICE.png',
  'usf': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/USF.png',
  'temple': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TEM.png',
  'tulane': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TULN.png',
  'tulsa': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TLSA.png',
  'uab': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UAB.png',
  'utsa': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UTSA.png',

  // PAC-12
  'washington state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WSU.png',
  'oregon state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ORST.png',

  // Mountain West
  'air force': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/AFA.png',
  'boise state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BOIS.png',
  'colorado state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CSU.png',
  'fresno state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FRES.png',
  'hawaii': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/HAW.png',
  'nevada': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NEV.png',
  'new mexico': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UNM.png',
  'san diego state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SDSU.png',
  'sdsu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SDSU.png', // San Diego State (not South Dakota State)
  'san jose state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SJSU.png',
  'unlv': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UNLV.png',
  'utah state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/USU.png',
  'wyoming': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WYO.png',

  // Sun Belt
  'appalachian state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/APP.png',
  'arkansas state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ARST.png',
  'coastal carolina': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CCU.png',
  'georgia southern': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/GASO.png',
  'georgia state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/GAST.png',
  'james madison': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/JMU.png',
  'jmu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/JMU.png',
  'louisiana': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UL.png',
  'louisiana-monroe': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ULM.png',
  'marshall': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MRSH.png',
  'old dominion': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ODU.png',
  'south alabama': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/USA.png',
  'southern miss': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/USM.png',
  'texas state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TXST.png',
  'troy': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TROY.png',

  // Conference USA
  'missouri state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MOST.png',
  'delaware': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UD.png',
  'florida international': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FIU.png',
  'fiu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FIU.png',
  'jacksonville state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/JVST.png',
  'kennesaw state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/KENN.png',
  'liberty': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LIB.png',
  'louisiana tech': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LT.png',
  'middle tennessee': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTSU.png',
  'middle tennessee state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTSU.png',
  'middle tennessee state university': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTSU.png',
  'middle tennessee blue raiders': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTSU.png',
  'mtsu': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTSU.png',
  'mt': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTSU.png',
  'new mexico state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NMSU.png',
  'sam houston': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SHSU.png',
  'utep': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UTEP.png',
  'western kentucky': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WKU.png',

  // Independents
  'connecticut': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CONN.png',
  'notre dame': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ND.png',

  // MAC
  'akron': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/AKR.png',
  'ball state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BALL.png',
  'bowling green': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BGSU.png',
  'buffalo': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BUFF.png',
  'central michigan': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CMU.png',
  'eastern michigan': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/EMU.png',
  'kent state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/KENT.png',
  'massachusetts': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MASS.png',
  'umass': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MASS.png',
  'miami (oh)': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/M-OH.png',
  'northern illinois': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NIU.png',
  'ohio': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/OHIO.png',
  'toledo': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TOL.png',
  'western michigan': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WMU.png',

  // FCS Schools
  'samford': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SAM.png',
  'northern arizona': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NAU.png',
  'cal poly': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CP.png',
  'sacramento state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SAC.png',
  'northern colorado': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UNCO.png',
  'central connecticut': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CCSU.png',
  'florida a&m': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FAMU.png',
  'bethune-cookman': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BCU.png',
  'mercer': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MER.png',
  'northern iowa': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UNI.png',
  'idaho': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/IDHO.png',
  'eastern illinois': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/EIU.png',
  'western illinois': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WIU.png',
  'eastern kentucky': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/EKU.png',
  'murray state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MUR.png',
  'mcneese': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MCN.png',
  'nicholls': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NICH.png',
  'northwestern state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NWST.png',
  'se louisiana': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SELA.png',
  'holy cross': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/HC.png',
  'merrimack': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MRMK.png',
  'morgan state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MORG.png',
  'towson': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TOW.png',
  'maine': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ME.png',
  'lindenwood': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LIN.png',
  'se missouri state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SEMO.png',
  'alcorn state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ALCN.png',
  'jackson state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/JKST.png',
  'montana state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MTST.png',
  'north carolina a&t': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NCAT.png',
  'campbell': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CAM.png',
  'north carolina central': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NCCU.png',
  'elon': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ELON.png',
  'gardner-webb': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/GWEB.png',
  'western carolina': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WCU.png',
  'north dakota': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UND.png',
  'new hampshire': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UNH.png',
  'monmouth': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MONM.png',
  'albany': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ALB.png',
  'colgate': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/COLG.png',
  'fordham': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FOR.png',
  'long island university': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LIU.png',
  'stony brook': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/STBK.png',
  'wagner': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WAG.png',
  'youngstown state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/YSU.png',
  'portland state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PRST.png',
  'bucknell': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BUCK.png',
  'duquesne': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/DUQ.png',
  'lafayette': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LAF.png',
  'robert morris': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/RMU.png',
  'st. francis (pa)': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SFPA.png',
  'villanova': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/VILL.png',
  'rhode island': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/URI.png',
  'charleston southern': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CHSO.png',
  'furman': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/FUR.png',
  'south carolina state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SCST.png',
  'the citadel': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CIT.png',
  'wofford': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WOF.png',
  'south dakota': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SDAK.png',
  'austin peay': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/APSU.png',
  'chattanooga': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UTC.png',
  'east tennessee state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ETSU.png',
  'ut martin': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UTM.png',
  'tennessee tech': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TNTC.png',
  'abilene christian': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ACU.png',
  'tarleton state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TAR.png',
  'houston christian': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/HCU.png',
  'lamar': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LAM.png',
  'prairie view a&m': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PV.png',
  'stephen f. austin': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SFA.png',
  'texas southern': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TXSO.png',
  'vmi': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/VMI.png',
  'norfolk state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NORF.png',
  'richmond': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/RICH.png',
  'william & mary': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/W&M.png',
  'eastern washington': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/EWU.png',
  'delaware state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/DSU.png',
  'howard': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/HOW.png',
  'arkansas-pine bluff': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UAPB.png',
  'illinois state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ILST.png',
  'indiana state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/INST.png',
  'uc davis': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UCD.png',
  'idaho state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/IDST.png',
  'central arkansas': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CARK.png',
  'north alabama': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UNA.png',
  'alabama a&m': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/AAMU.png',
  'southern illinois': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SIU.png',
  'grambling': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/GRAM.png',
  'alabama state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ALASU.png',
  'southern': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SOU.png',
  'weber state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/WEB.png',
  'incarnate word': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/IW.png',
  'bryant': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BRY.png',
  'east texas a&m': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ETAMU.png',
  'hampton': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/HAMP.png',
  'mercyhurst': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MCY.png',
  'montana': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MON.png',
  'south dakota state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SDST.png',
  'sdst': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SDST.png', // South Dakota State (not San Diego State)
  'stonehill': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/STO.png',
  'west georgia': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UWG.png',
  'utrgv': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TRGV.png',
  'tennessee state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/TSU.png',
  'southern utah': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SUU.png',
  'sacred heart': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/SHU.png',
  'utah tech': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UTT.png',

  // Ivy League
  'brown': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BRWN.png',
  'columbia': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/CLMB.png',
  'cornell': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/COR.png',
  'dartmouth': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/DART.png',
  'harvard': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/HARV.png',
  'penn': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PENN.png',
  'pennsylvania': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PENN.png',
  'princeton': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PCT.png',
  'yale': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/YALE.png',

  // Pioneer Football League
  'butler': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/BUT.png',
  'davidson': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/DAV.png',
  'dayton': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/DAY.png',
  'drake': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/DRKE.png',
  'valparaiso': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/VAL.png',

  // Other FCS
  'georgetown': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/GTWN.png',
  'lehigh': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/LEH.png',
  'marist': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MRST.png',
  'mississippi valley state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MVSU.png',
  'morehead state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/MORE.png',
  'north dakota state': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/NDSU.png',
  'presbyterian': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/PRES.png',
  'st. thomas': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/UST.png',
  'san diego': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/USD.png',
  'stetson': 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/STET.png',
}

export function getTeamLogo(teamName: string): string {
  const team = teamName.toLowerCase().trim()

  // Try exact match first
  if (cfbTeams[team]) {
    return cfbTeams[team]
  }

  // If no exact match, check if the team name starts with any known team ID
  // This handles cases where mascot is included (e.g., "Texas Tech Red Raiders" -> "texas tech")
  for (const knownTeam of allTeams) {
    const teamId = knownTeam.id.toLowerCase()
    if (team.startsWith(teamId + ' ') || team === teamId) {
      if (cfbTeams[teamId]) {
        return cfbTeams[teamId]
      }
    }
  }

  // Also check the keys in cfbTeams directly for partial matches
  // Sort keys by length (longest first) to match more specific names first
  // This ensures "texas a&m" is checked before "texas"
  const sortedKeys = Object.keys(cfbTeams).sort((a, b) => b.length - a.length);
  for (const key of sortedKeys) {
    if (team.startsWith(key + ' ') || team === key) {
      return cfbTeams[key]
    }
  }

  // Default fallback - NCAA logo for schools not in our database (FCS, D2, etc.)
  return 'https://staticd.profootballnetwork.com/skm/assets/college-football-playoff-predictor/team-logos/ncaa.png'
}
